module.exports = [
    {
        id: 1,
        first_name: "Matt",
        last_name: "Meyer",
        password: "password123", // You should hash the password in a real application
        alias: "matt_meyer",
        street: "123 Main Street",
        city: "Nashville",
        state: "Tennessee",
        zip: "37217",
        country: "United States of America",
        lat: 36.1627, // Replace with actual latitude
        long: -86.7744, // Replace with actual longitude
        email: "matt@example.com",
        phone: "615-555-5555",
        can_text: false,
        pic: "https://media.licdn.com/dms/image/C5603AQEZn6MDgHg0Rg/profile-displayphoto-shrink_800_800/0/1517594081948?e=2147483647&v=beta&t=ONTM4QGay73I8WXm_nxd1Q7ow8QuPy6SqH24H8hK3a0",
        social_ig: "matt_ig",
        social_facebook: "matt_facebook",
        social_soundcloud: "matt_soundcloud",
        social_youtube: null,
        social_linkedin: "matt_linkedin",
        portfolioLink1: "https://portfolio1.com",
        portfolioLink2: null,
        portfolioLink3: null,
        bio: "Passionate about teaching the guitar. Excited to connect with fellow music mentee enthusiasts!",
    },
    {
        id: 2,
        first_name: 'Dan',
        last_name: 'Brown',
        password: 'mentee_password',
        alias: 'MenteeAlias',
        street: '456 Second Street',
        city: "Atlanta",
        state: "Georgia",
        zip: "30002",
        country: "United States of America",
        lat: 33.7490, // Replace with the actual latitude
        long: -84.3880, // Replace with the actual longitude
        email: 'dan.brown@example.com',
        phone: '123-456-7890',
        can_text: false,
        pic: 'https://hips.hearstapps.com/hmg-prod/images/701/dating-app-photo-mistakes-main-1515525122.jpg',
        social_ig: 'dan_brown_ig',
        social_facebook: 'john.doe.facebook',
        social_soundcloud: 'john_doe_soundcloud',
        social_youtube: null,
        social_linkedin: 'john_doe_linkedin',
        portfolioLink1: null,
        portfolioLink2: null,
        portfolioLink3: null,
        bio: "I am passionate about learning guitar and exploring various genres.",
    },
    {
        id: 3,
        first_name: 'Jerry',
        last_name: 'Cantrell',
        password: 'your_password', // Replace with an appropriate password
        alias: 'Jerry',
        street: '123 Main St', // Replace with an appropriate address
        city: 'Tacoma',
        state: 'Washington',
        zip: '98001', // Replace with an appropriate zip code
        country: 'United States of America',
        lat: 47.2529, // Replace with appropriate latitude
        long: -122.4443, // Replace with appropriate longitude
        email: 'jerry@aliceinchains.com', // Replace with an appropriate email
        phone: '555-555-5555', // Replace with an appropriate phone number
        can_text: false,
        pic: 'https://imageio.forbes.com/specials-images/imageserve/626980c1496065da495a6d82/Jerry-Cantrell-poses-in-Chicago-on-night-two-of-the--Brighten--tour--Saturday--March/960x0.jpg?format=jpg&width=960', // Replace with an appropriate profile image path
        social_ig: 'jerrycantrell', // Replace with appropriate social media usernames
        social_facebook: 'JerryCantrell',
        social_soundcloud: 'jerrycantrellsound',
        social_youtube: null,
        social_linkedin: 'jerry-cantrell',
        portfolioLink1: 'https://www.aliceinchains.com', // Alice In Chains official site
        portfolioLink2: null,
        portfolioLink3: null,
        bio: 'Lead guitarist in Alice In Chains since the band was formed.',
    },
    {
        id: 4,
        first_name: 'Rabea',
        last_name: 'Massaad',
        password: 'your_password', // Replace with an appropriate password
        alias: 'Rabea',
        street: '456 Oak St', // Replace with an appropriate address
        city: 'Brighton',
        state: 'England',
        zip: 'BN1 1AB', // Replace with an appropriate zip code
        country: 'United Kingdom',
        lat: 50.8225, // Replace with appropriate latitude
        long: -0.1372, // Replace with appropriate longitude
        email: 'rabea@example.com', // Replace with an appropriate email
        phone: '555-555-5555', // Replace with an appropriate phone number
        can_text: false,
        pic: 'https://chapmanguitars.s3.eu-west-1.amazonaws.com/wp-content/uploads/2021/02/10124542/980x980-Rabea-Massaad_Profile-Image-490x490.png', // Replace with an appropriate profile image path
        social_ig: 'rabeaafro',
        social_facebook: null,
        social_soundcloud: null,
        social_youtube: null,
        social_linkedin: 'linkedin.com/in/rabea-massaad-475b1524',
        portfolioLink1: 'https://www.rabeamassaad.com/', // Rabea's main portfolio site
        portfolioLink2: 'https://Instagram.com/rabeaafro',
        portfolioLink3: 'https://www.YouTube.com/rabeaafro',
        bio: "Hey there! I'm Rabea Massaad, a guitarist hailing from Brighton, England. You may know me from my YouTube channel 'rabeaafro,' where I share my love for music and guitar. As a mentor on MentorMe, I'm here to guide you through the intricacies of guitar playing, offering insights from my real-world experience. Let's explore the fretboard, discover new techniques, and unleash the power of music together. Join me on this exciting journey at MentorMe!",
    },
    {
        id: 5,
        first_name: 'Paul',
        last_name: 'Davids',
        password: 'securepassword', // You may want to use a secure password hashing method
        alias: 'PaulDavids',
        street: '123 Guitar Street',
        city: 'Rotterdam',
        state: 'South Holland',
        zip: '1234 AB',
        country: 'Netherlands',
        lat: 51.9225, // Example coordinates for Rotterdam
        long: 4.47917,
        email: 'paul.davids@example.com',
        phone: '555-555-5555',
        can_text: false,
        pic: 'https://maybach-guitars.de/wp-content/uploads/2022/06/Paul-Davids-with-Salmon.jpg',
        social_ig: 'https://instagram.com/pauldavidsguitar',
        social_facebook: 'https://www.facebook.com/pauldavids',
        social_soundcloud: null,
        social_youtube: 'https://www.youtube.com/@PaulDavids',
        social_linkedin: null,
        portfolioLink1: 'https://www.pauldavids.com/',
        portfolioLink2: null,
        portfolioLink3: null,
        bio: `Hey there, I'm Paul Davids - a passionate guitarist, music educator, and content creator. I've been sharing my love for the guitar on my YouTube channel, where I provide tutorials, gear reviews, and insights into the world of music.
        As a guitarist, I believe in the power of music to inspire and connect people. Join me on a musical journey where we explore techniques, theory, and the joy of playing the guitar. I'm excited to be a mentor on MentorMe, where I can share my knowledge and help fellow guitar enthusiasts reach their musical goals.
        See you in the world of strings and frets! 🎸`,
    },
    {
        id: 6,
        first_name: 'Paul',
        last_name: 'Nieto',
        password: 'securepassword', // You may want to use a secure password hashing method
        alias: 'PNieto',
        street: '207 W 14th St',
        city: 'New York City',
        state: 'NY',
        zip: '10011',
        country: 'United States of America',
        lat: 40.7387, // Example coordinates for Rotterdam
        long: -74.0001,
        email: 'Pnieto10@gmail.com',
        phone: '212-675-3260',
        can_text: false,
        pic: 'https://i.ytimg.com/vi/U58WL9Iu3Oc/hqdefault.jpg',
        social_ig: 'https://instagram.com/guitartech.nyc',
        social_facebook: 'https://www.facebook.com/theRumberos',
        social_soundcloud: null,
        social_youtube: 'https://www.youtube.com/user/LaMarotte2',
        social_linkedin: null,
        portfolioLink1: "https://www.guitartechny.com/Home.html",
        portfolioLink2: null,
        portfolioLink3: null,
        bio: `Hey there, I'm Paul. I'm the owner and master luthier of Guitar Tech NYC. I'm on here to train and connect with some of the best and brightest who want to learn to become master luthiers.`,
    },
    {
        id: 7,
        first_name: 'Rick',
        last_name: 'Beato',
        password: 'your_secure_password',
        alias: 'rickbeato',
        street: '123 Music Street',
        city: 'Atlanta',
        state: 'Georgia',
        zip: '30301',
        country: 'United States of America',
        lat: 33.7490,
        long: -84.3880,
        email: 'rick@example.com',
        phone: '555-555-1234',
        can_text: false,
        pic: 'https://cdn.mos.cms.futurecdn.net/XhxC5f5gUgEjcVBt3P3qsi.jpg',
        social_ig: 'https://instagram.com/rickbeato1',
        social_facebook: 'https://facebook.com/rick.beato',
        social_soundcloud: null,
        social_youtube: 'https://www.youtube.com/c/RickBeato',
        social_linkedin: null,
        portfolioLink1: 'https://www.youtube.com/@rickbeato240',
        portfolioLink2: null,
        portfolioLink3: null,
        bio: 'Music producer, educator, and YouTuber known for his insightful breakdowns of songs, music theory lessons, and music production tips. With a wealth of experience in the music industry, Rick Beato shares his knowledge to help musicians and music enthusiasts deepen their understanding of music.',
    },
    {
        id: 8,
        first_name: 'Jonathan',
        last_name: 'Silva',
        password: 'your_secure_password',
        alias: 'johnny5ive167',
        street: '123 Bunker Street',
        city: 'Middle Island',
        state: 'New York',
        zip: '11953',
        country: 'United States of America',
        lat: 40.8833,
        long: -72.9450,
        email: 'jonathan.silva167@gmail.com',
        phone: '555-555-1234',
        can_text: false,
        pic: 'https://media.licdn.com/dms/image/C5103AQHC-EnKQk3hbQ/profile-displayphoto-shrink_800_800/0/1517364614311?e=2147483647&v=beta&t=aDsR-1DgZviO019cpRFtY76G4efGIw_DvemvmgFzTpw',
        social_ig: 'https://instagram.com/artbyjs',
        social_facebook: null,
        social_soundcloud: null,
        social_youtube: null,
        social_linkedin: 'https://www.linkedin.com/in/jonathansilva761/',
        portfolioLink1: 'https://intenebrisbyjs.com',
        portfolioLink2: "https://github.com/jon-slva",
        portfolioLink3: "https://jewelrybyjs.com",
        bio: 'Just a guy who does a lot of things and is passinonate about learning.',
    },
];