module.exports = [
    { id: 1, name: 'Guitarist' },
    { id: 2, name: 'Luthier' },
    { id: 3, name: 'Traditional Art' },
    { id: 4, name: '2D Animation' },
    { id: 5, name: '3D Design' },
    { id: 6, name: 'Photography' },
    { id: 7, name: 'Digital Marketing' },
    { id: 8, name: 'Cooking' },
    { id: 9, name: 'Personal Finance' },
    { id: 10, name: 'Fitness & Nutrition' },
    { id: 11, name: 'Creative Writing' },
    { id: 12, name: 'Language Learning' },
    { id: 13, name: 'Mindfulness & Meditation' },
    { id: 14, name: 'Introduction to Astronomy' },
    { id: 15, name: 'Gardening' },
    { id: 16, name: 'Web Development' },
];